import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  let role: string | null = null;

  if (token) {
    try {
      const secret = new TextEncoder().encode(process.env.JWT_SECRET);
      const { payload } = await jwtVerify(token, secret);
      role = (payload.role as string) || null;
    } catch (error) {
      console.error("Token invalid or expired:", error);
      cookieStore.delete("token");
    }
  }

  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <AuthProvider initialRole={role} initialToken={token}>
          {children}
          <Toaster position="top-right" duration={5000} />
        </AuthProvider>
      </body>
    </html>
  );
}
